server:
  port: 9000
  
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
      routes:
        #Route Mapping
      - id: masterDataMicroservice             
        uri: http://localhost:9090/
        predicates:
        - Path=/dataservice/**      
        
      - id: connectionMicroservice
        uri: http://localhost:8080
        predicates:
        - Path=/connectionservice/**